name: CI

on: [ push ]

jobs:
  clean-build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build
      # currently we cannot move it into other jobs because of "not a git repository" issue
      - name: Build Test Reports
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Test Reports
          path: '**/TEST-*.xml'
          reporter: java-junit
#          max-annotations: '0' # enable it after we can use it to disable listing
#      - name: Upload Test Reports
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-reports
#          path: build/test-results/
#      - name: Build Coverage Reports
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.3
#        with:
#          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 40
#          min-coverage-changed-files: 60
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2.8.1
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
  generate-open-api-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Generate OpenAPI Document
        run: ./gradlew clean generateOpenApiDocs
      - name: Upload OpenAPI Document
        uses: actions/upload-artifact@v3
        with:
          name: open-api-doc
          path: build/openapi.json
