name: CI

on: [ push ]

jobs:
  clean-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/test-results/
  #      - name: Publish Coverage Report
  #        uses: madrapps/jacoco-report@v1.3
  #        with:
  #          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
  #          token: ${{ secrets.GITHUB_TOKEN }}
  #          min-coverage-overall: 40
  #          min-coverage-changed-files: 60
  generate-test-reports:
    needs: [ clean-build ]
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Download Test Reports
        uses: actions/download-artifact@v3
        with:
          name: test-reports
          path: build/test-results/
      - name: Build Test Reports
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Test Reports
          path: '**/build/test-results/**/TEST-*.xml'
          reporter: java-junit
          max-annotations: 0
#  generate-open-api-doc:
#    needs: [ clean-build ]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Generate OpenAPI doc
#        run: ./gradlew clean generateOpenApiDocs
