name: GitHub Actions Demo

on: [push]

jobs:
  clean-build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build
      - name: Build Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Test Report
          path: '**/build/test-results/**/TEST-*.xml'
          reporter: java-junit
      - name: Publish Coverage Report
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
      - name: Generate OpenAPI doc
        run: ./gradlew clean generateOpenApiDocs
