name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Test Reports
          path: '**/build/test-results/**/TEST-*.xml'
          reporter: java-junit
